CREATE TABLE delivery
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title character varying(50) NOT NULL,
  CONSTRAINT delivery_pkey PRIMARY KEY (id)
);

CREATE TABLE orders
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_description character varying(50) NOT NULL,
  delivery_id BIGINT NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_fkey FOREIGN KEY (delivery_id) REFERENCES delivery(id)

);

CREATE TABLE tag
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  value character varying(50) NOT NULL,
  order_id BIGINT NOT NULL,
  CONSTRAINT tag_pkey PRIMARY KEY (id),
  CONSTRAINT tag_order_fkey FOREIGN KEY (order_id) REFERENCES orders(id)
);


