CREATE TABLE orders
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_description character varying(50) NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (id)
);

CREATE TABLE tag
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  value character varying(50) NOT NULL,
  order_id BIGINT NOT NULL,
  CONSTRAINT tag_pkey PRIMARY KEY (id),
  CONSTRAINT tag_order_fkey FOREIGN KEY (order_id) REFERENCES orders(id)
);



