CREATE TABLE delivery
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title character varying(50) NOT NULL,
  CONSTRAINT delivery_pkey PRIMARY KEY (id)
);

CREATE TABLE orders
(
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_description character varying(50) NOT NULL,
  delivery_id BIGINT NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (order_id),
  CONSTRAINT delivery_fkey FOREIGN KEY (delivery_id) REFERENCES delivery(id)
);


